"""empty message

Revision ID: 2c704554671b
Revises: 805e879fe352
Create Date: 2022-01-04 17:23:05.292993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c704554671b'
down_revision = '805e879fe352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('user_total_bounty_collected', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'user_total_bounty_collected')
    # ### end Alembic commands ###
