"""empty message

Revision ID: 4dd999a91b40
Revises: 
Create Date: 2021-11-12 20:27:09.895888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd999a91b40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cash_on_hand', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('cash_in_bank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cash_in_bank')
    op.drop_column('user', 'cash_on_hand')
    # ### end Alembic commands ###
