"""empty message

Revision ID: 54c7ec611530
Revises: e7b5ae768f27
Create Date: 2021-11-28 00:54:22.615602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c7ec611530'
down_revision = 'e7b5ae768f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('user_max_health', sa.Integer(), nullable=True))
    op.add_column('user__stats', sa.Column('user_in_icu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'user_in_icu')
    op.drop_column('user__stats', 'user_max_health')
    # ### end Alembic commands ###
