"""empty message

Revision ID: a769395b6d31
Revises: 4dd999a91b40
Create Date: 2021-11-19 19:12:16.522379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a769395b6d31'
down_revision = '4dd999a91b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('item_image', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.String(length=255), nullable=True),
    sa.Column('item_attack', sa.Integer(), nullable=True),
    sa.Column('item_defense', sa.Integer(), nullable=True),
    sa.Column('item_cost', sa.Integer(), nullable=True),
    sa.Column('item_sell', sa.Integer(), nullable=True),
    sa.Column('item_decay', sa.Integer(), nullable=True),
    sa.Column('item_repair', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__items')
    op.drop_table('item')
    # ### end Alembic commands ###
