"""empty message

Revision ID: abc3f578166c
Revises: c9351f7cff22
Create Date: 2021-12-25 15:27:12.541961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc3f578166c'
down_revision = 'c9351f7cff22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('user_current_bounty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'user_current_bounty')
    # ### end Alembic commands ###
