"""empty message

Revision ID: b90616c60f40
Revises: 36b1c6df5e6c
Create Date: 2021-12-20 03:41:25.504327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90616c60f40'
down_revision = '36b1c6df5e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_region', sa.String(length=128), nullable=False),
    sa.Column('mission_name', sa.String(length=128), nullable=False),
    sa.Column('mission_image', sa.String(length=128), nullable=False),
    sa.Column('mission_tier', sa.String(length=24), nullable=False),
    sa.Column('mission_required_mastery', sa.Integer(), nullable=False),
    sa.Column('mission_required_energy', sa.Integer(), nullable=False),
    sa.Column('mission_required_item_id', sa.Integer(), nullable=False),
    sa.Column('mission_required_mobc', sa.Integer(), nullable=False),
    sa.Column('mission_reward_min_xp', sa.Integer(), nullable=False),
    sa.Column('mission_reward_max_xp', sa.Integer(), nullable=False),
    sa.Column('mission_reward_min_cash', sa.Integer(), nullable=False),
    sa.Column('mission_reward_max_cash', sa.Integer(), nullable=False),
    sa.Column('mission_reward_skill_points', sa.Integer(), nullable=False),
    sa.Column('mission_reward_mobc', sa.Integer(), nullable=False),
    sa.Column('mission_reward_item_id', sa.Integer(), nullable=False),
    sa.Column('mission_reward_turf_id', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_min_xp', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_max_xp', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_min_cash', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_max_cash', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_skill_points', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_mobc', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_item_id', sa.Integer(), nullable=False),
    sa.Column('mission_mastery_reward_turf_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_name')
    )
    op.add_column('user__stats', sa.Column('user_current_mission_id', sa.Integer(), nullable=True))
    op.add_column('user__stats', sa.Column('user_current_mission_stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'user_current_mission_stage')
    op.drop_column('user__stats', 'user_current_mission_id')
    op.drop_table('missions')
    # ### end Alembic commands ###
