"""empty message

Revision ID: c9351f7cff22
Revises: 165a53544341
Create Date: 2021-12-24 01:01:13.313668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9351f7cff22'
down_revision = '165a53544341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('user_on_hitlist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'user_on_hitlist')
    # ### end Alembic commands ###
