"""empty message

Revision ID: ca165bdf857d
Revises: 54c7ec611530
Create Date: 2021-12-06 01:04:22.945863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca165bdf857d'
down_revision = '54c7ec611530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('user_total_income', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'user_total_income')
    # ### end Alembic commands ###
