"""empty message

Revision ID: ed902097b641
Revises: b90616c60f40
Create Date: 2021-12-20 15:29:42.177346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed902097b641'
down_revision = 'b90616c60f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__stats', sa.Column('user_current_energy', sa.Integer(), nullable=True))
    op.add_column('user__stats', sa.Column('user_max_energy', sa.Integer(), nullable=True))
    op.add_column('user__stats', sa.Column('user_energy_thread_running', sa.Boolean(), nullable=True))
    op.add_column('user__stats', sa.Column('user_current_stamina', sa.Integer(), nullable=True))
    op.add_column('user__stats', sa.Column('user_max_stamina', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__stats', 'user_max_stamina')
    op.drop_column('user__stats', 'user_current_stamina')
    op.drop_column('user__stats', 'user_energy_thread_running')
    op.drop_column('user__stats', 'user_max_energy')
    op.drop_column('user__stats', 'user_current_energy')
    # ### end Alembic commands ###
